file-hashes = { sha256 = "7b3f2838a1a906bad0e78a80328cd2a6b0a6227bb3e7012e5c5b8dd1e78e828c" }
version = "1.0"
created-at = 2024-02-25T22:26:04.060012+00:00
indexes = ["https://pypi.org/simple"]
dependencies = ["hatchling", "mousebender", "numpy", "pydantic", "requests"]

[[lock]]
markers = []
tags = ['cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64', 'py3-none-any']

[[lock.wheel]]
name = "annotated-types"
filename = "annotated_types-0.6.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl"
hashes = { sha256 = '0641064de18ba7a25dee8f96403ebc39113d0cb953a01429249d5c7564666a43' }
direct = false
requires-python = ">=3.8"
dependencies = []

[[lock.wheel]]
name = "certifi"
filename = "certifi-2024.2.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/ba/06/a07f096c664aeb9f01624f858c3add0a4e913d6c96257acb4fce61e7de14/certifi-2024.2.2-py3-none-any.whl"
hashes = { sha256 = 'dc383c07b76109f368f6106eee2b593b04a011ea4d55f652c6ca24a754d1cdd1' }
direct = false
requires-python = ">=3.6"
dependencies = []

[[lock.wheel]]
name = "charset-normalizer"
filename = "charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
origin = "https://files.pythonhosted.org/packages/ee/fb/14d30eb4956408ee3ae09ad34299131fb383c47df355ddb428a7331cfa1e/charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
hashes = { sha256 = '90d558489962fd4918143277a773316e56c72da56ec7aa3dc3dbbe20fdfed15b' }
direct = false
requires-python = ">=3.7.0"
dependencies = []

[[lock.wheel]]
name = "editables"
filename = "editables-0.5-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl"
hashes = { sha256 = '61e5ffa82629e0d8bfe09bc44a07db3c1ab8ed1ce78a6980732870f19b5e7d4c' }
direct = false
requires-python = ">=3.7"
dependencies = []

[[lock.wheel]]
name = "hatchling"
filename = "hatchling-1.21.1-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/3a/bb/40528a09a33845bd7fd75c33b3be7faec3b5c8f15f68a58931da67420fb9/hatchling-1.21.1-py3-none-any.whl"
hashes = { sha256 = '21e8c13f8458b219a91cb84e5b61c15bf786695d1c4fabc29e91e78f94bfe892' }
direct = false
requires-python = ">=3.8"
dependencies = ["editables", "packaging", "pathspec", "pluggy", "trove-classifiers"]

[[lock.wheel]]
name = "idna"
filename = "idna-3.6-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/c2/e7/a82b05cf63a603df6e68d59ae6a68bf5064484a0718ea5033660af4b54a9/idna-3.6-py3-none-any.whl"
hashes = { sha256 = 'c05567e9c24a6b9faaa835c4821bad0590fbb9d5779e7caa6e1cc4978e7eb24f' }
direct = false
requires-python = ">=3.5"
dependencies = []

[[lock.wheel]]
name = "mousebender"
filename = "mousebender-2023.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/db/c1/b0f7859dc59d527cbcade44f81453158f8b782cbeeb8acb5b5b27f1fbdfc/mousebender-2023.2-py3-none-any.whl"
hashes = { sha256 = 'b14d382f26bad190f9fa6f11716f0c3f16588517739554db90102ad0cf156ac1' }
direct = false
requires-python = ">=3.8"
dependencies = ["packaging", "typing-extensions"]

[[lock.wheel]]
name = "numpy"
filename = "numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
origin = "https://files.pythonhosted.org/packages/0f/50/de23fde84e45f5c4fda2488c759b69990fd4512387a8632860f3ac9cd225/numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
hashes = { sha256 = '675d61ffbfa78604709862923189bad94014bef562cc35cf61d3a07bba02a7ed' }
direct = false
requires-python = ">=3.9"
dependencies = []

[[lock.wheel]]
name = "packaging"
filename = "packaging-23.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl"
hashes = { sha256 = '8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7' }
direct = false
requires-python = ">=3.7"
dependencies = []

[[lock.wheel]]
name = "pathspec"
filename = "pathspec-0.12.1-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl"
hashes = { sha256 = 'a0d503e138a4c123b27490a4f7beda6a01c6f288df0e4a8b79c7eb0dc7b4cc08' }
direct = false
requires-python = ">=3.8"
dependencies = []

[[lock.wheel]]
name = "pluggy"
filename = "pluggy-1.4.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/a5/5b/0cc789b59e8cc1bf288b38111d002d8c5917123194d45b29dcdac64723cc/pluggy-1.4.0-py3-none-any.whl"
hashes = { sha256 = '7db9f7b503d67d1c5b95f59773ebb58a8c1c288129a88665838012cfb07b8981' }
direct = false
requires-python = ">=3.8"
dependencies = []

[[lock.wheel]]
name = "pydantic"
filename = "pydantic-2.6.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/42/28/f19be8d493c59a8ddf32c15d69765c6423ad712da1c6255b418df2fc1443/pydantic-2.6.2-py3-none-any.whl"
hashes = { sha256 = '37a5432e54b12fecaa1049c5195f3d860a10e01bdfd24f1840ef14bd0d3aeab3' }
direct = false
requires-python = ">=3.8"
dependencies = ["annotated-types", "pydantic-core", "typing-extensions"]

[[lock.wheel]]
name = "pydantic-core"
filename = "pydantic_core-2.16.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
origin = "https://files.pythonhosted.org/packages/dc/df/cd1cdd79a307c06fbea11be2cd8f361604b82f9b28c7712bd1220c44f226/pydantic_core-2.16.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
hashes = { sha256 = '500960cb3a0543a724a81ba859da816e8cf01b0e6aaeedf2c3775d12ee49cade' }
direct = false
requires-python = ">=3.8"
dependencies = ["typing-extensions"]

[[lock.wheel]]
name = "requests"
filename = "requests-2.31.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl"
hashes = { sha256 = '58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f' }
direct = false
requires-python = ">=3.7"
dependencies = ["certifi", "charset-normalizer", "idna", "urllib3"]

[[lock.wheel]]
name = "trove-classifiers"
filename = "trove_classifiers-2024.2.23-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/56/45/6887993f3d1fd941fe129c8dc3aa648d5bd20e0e02c08f99df961fd1e908/trove_classifiers-2024.2.23-py3-none-any.whl"
hashes = { sha256 = '3094534b8021dc1822aadb1d11d4c7b62a854d464d19458fd0a49d6fe2b68b77' }
direct = false
dependencies = []

[[lock.wheel]]
name = "typing-extensions"
filename = "typing_extensions-4.10.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/f9/de/dc04a3ea60b22624b51c703a84bbe0184abcd1d0b9bc8074b5d6b7ab90bb/typing_extensions-4.10.0-py3-none-any.whl"
hashes = { sha256 = '69b1a937c3a517342112fb4c6df7e72fc39a38e7891a5730ed4985b5214b5475' }
direct = false
requires-python = ">=3.8"
dependencies = []

[[lock.wheel]]
name = "urllib3"
filename = "urllib3-2.2.1-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl"
hashes = { sha256 = '450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d' }
direct = false
requires-python = ">=3.8"
dependencies = []
