file-hashes = { sha256 = "19380a1e2ed182dd01d70029279b95218b525f6372d279b05e806094e5d48e56" }
version = "1.0"
created-at = 2024-02-25T02:31:37.738138+00:00
indexes = ["https://pypi.org/simple"]
dependencies = ["rich"]

[[lock]]
markers = { python_full_version = '3.12.0', python_version = '3.12' }
tags = ['py312-none-any', 'py3-none-any', 'py311-none-any', 'py310-none-any', 'py39-none-any', 'py38-none-any', 'py37-none-any', 'py36-none-any', 'py35-none-any', 'py34-none-any', 'py33-none-any', 'py32-none-any', 'py31-none-any', 'py30-none-any']

[[lock.wheel]]
name = "markdown-it-py"
filename = "markdown_it_py-3.0.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl"
hashes = { sha256 = '355216845c60bd96232cd8d8c40e8f9765cc86f46880e43a8fd22dc1a1a8cab1' }
direct = false
requires-python = ">=3.8"

[[lock.wheel]]
name = "mdurl"
filename = "mdurl-0.1.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl"
hashes = { sha256 = '84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8' }
direct = false
requires-python = ">=3.7"

[[lock.wheel]]
name = "pygments"
filename = "pygments-2.17.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl"
hashes = { sha256 = 'b27c2826c47d0f3219f29554824c30c5e8945175d888647acd804ddd04af846c' }
direct = false
requires-python = ">=3.7"

[[lock.wheel]]
name = "rich"
filename = "rich-13.7.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/be/be/1520178fa01eabe014b16e72a952b9f900631142ccd03dc36cf93e30c1ce/rich-13.7.0-py3-none-any.whl"
hashes = { sha256 = '6da14c108c4866ee9520bbffa71f6fe3962e193b7da68720583850cd4548e235' }
direct = false
requires-python = ">=3.7.0"


[[lock]]
markers = { python_full_version = '3.8.0', python_version = '3.8' }
tags = ['py38-none-any', 'py3-none-any', 'py37-none-any', 'py36-none-any', 'py35-none-any', 'py34-none-any', 'py33-none-any', 'py32-none-any', 'py31-none-any', 'py30-none-any']

[[lock.wheel]]
name = "markdown-it-py"
filename = "markdown_it_py-3.0.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl"
hashes = { sha256 = '355216845c60bd96232cd8d8c40e8f9765cc86f46880e43a8fd22dc1a1a8cab1' }
direct = false
requires-python = ">=3.8"
dependencies = ["mdurl"]

[[lock.wheel]]
name = "mdurl"
filename = "mdurl-0.1.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl"
hashes = { sha256 = '84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8' }
direct = false
requires-python = ">=3.7"
dependencies = []

[[lock.wheel]]
name = "pygments"
filename = "pygments-2.17.2-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl"
hashes = { sha256 = 'b27c2826c47d0f3219f29554824c30c5e8945175d888647acd804ddd04af846c' }
direct = false
requires-python = ">=3.7"
dependencies = []

[[lock.wheel]]
name = "rich"
filename = "rich-13.7.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/be/be/1520178fa01eabe014b16e72a952b9f900631142ccd03dc36cf93e30c1ce/rich-13.7.0-py3-none-any.whl"
hashes = { sha256 = '6da14c108c4866ee9520bbffa71f6fe3962e193b7da68720583850cd4548e235' }
direct = false
requires-python = ">=3.7.0"
dependencies = ["markdown-it-py", "pygments", "typing-extensions"]

[[lock.wheel]]
name = "typing-extensions"
filename = "typing_extensions-4.9.0-py3-none-any.whl"
origin = "https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl"
hashes = { sha256 = 'af72aea155e91adfc61c3ae9e0e342dbc0cba726d6cba4b6c72c1f34e47291cd' }
direct = false
requires-python = ">=3.8"
dependencies = []