# Terminology:
#  environment -- A Python interpreter and OS that a lock entry targets.

# Inline table of hashes of this file w/o this line (including the newline); algorithm/value pairs.
# This helps detect if someone accidentally modified the file by hand.
file-hashes = {_ = "..."}
# Version the file.
# Since this file is designed to be human-readable but machine-writable, versioning makes sense as
# we don't need to keep a backwards-compatible format for humans.
version = "1.0"

dependencies = ["..."]  # Array of top-levl dependency specifiers.

# An environment's lock entry.
[[lock]]
markers = { _ = "..."}  # Inline table of environment markers.
tags = ["..."]  # Array of supported tag triples

# A wheel file.
[[lock.wheel]]
filename = "..."  # The wheel's file name.
origin = "..."  # URL or file path where the wheel was found.
hashes = { _ = "..." }  # Inline table of file hashes; algorithm/value pairs.
direct = false  # Whether `origin` is the direct URL in terms of `direct_url.json`.
requires-python = "..."  # Python version requirement (optional).
dependencies = ["..."]  # A list of project names which this project depends on. XXX include extras?

[[lock.sdist]]
# XXX filename
# XXX origin
# XXX hashes
# XXX direct
# XXX requires-python
# XXX dependencies (include extras?); Only if Metadata-Version >= 2.2 or always build to get?
# XXX lock build-system.requires ? https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-build-system-dependencies-the-build-system-table

[[lock.git]]  # https://pip.pypa.io/en/stable/topics/vcs-support/
# XXX name
# XXX repo URL
# XXX commit
# XXX requires-python
# XXX dependencies only if `pyproject.toml` or build as necessary?
# XXX lock build-system.requires ?
