# Terminology:
#  environment -- A Python interpreter and OS that a lock entry targets.
#  lock entry -- The locked project files for a specific environment.

# Inline table of hashes of this file w/o this line (including the newline); algorithm:value pairs.
# This helps detect if someone accidentally modified the file by hand.
file-hashes = {_ = "..."}
# Version the file.
# Since this file is designed to be human-readable but machine-writable,
#versioning makes sense as we don't need to keep a backwards-compatible format
# for humans.
version = "1.0"

# Array of top-level dependency specifiers.
# Includes all dependency specifiers necessary to generate a lock file entry
# given a specific environment.
dependencies = ["..."]

# An environment's lock entry.
[[lock]]
markers = { _ = "..."}  # Inline table of environment markers.
tags = ["..."]  # Array of supported tag triples

# A wheel file.
[[lock.wheel]]
# The project's normalized name.
# Cannot solely rely on the wheel filename to calculate this as the file name
# may not be a valid `.whl` file name due to
# https://packaging.python.org/en/latest/specifications/version-specifiers/#direct-references .
name = "..."
# The wheel's file name (optional due to direct references making the file name
# potentially not a valid `.whl` file name).
filename = "..."
# URL or file path (via `file://`) where the wheel that was locked against was found.
origin = "..."
hashes = { _ = "..." }  # Inline table of file hashes; algorithm:value pairs.
direct = false  # Whether `origin` is the direct URL in terms of `direct_url.json`.
requires-python = "..."  # Python version requirement (optional).
# A list of project names which this project depends on.
# Each entry can be just the project name as though the lock entry overall was
# the entire worldview of projects available (perk of Python not allowing
# multiple project versions simultaneously).
dependencies = ["..."]

[[lock.sdist]]
# XXX name
# XXX filename
# XXX origin
# XXX hashes
# XXX direct
# XXX requires-python
# XXX dependencies; only if Metadata-Version >= 2.2 and Requires-Dist not dynamic or build if necessary?
# XXX [[build-requires]] same as [[lock]]? Always or only if Metadata-Version < 2.2 or Requires-Dist is dynamic? https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-build-system-dependencies-the-build-system-table

# https://packaging.python.org/en/latest/specifications/version-specifiers/#direct-references
[[lock.git]]
# XXX name
# XXX repo URL
# XXX commit
# XXX requires-python
# XXX dependencies only if `pyproject.toml` and `projecct.dependencies` not dynamic or build as needed?
# XXX lock build-system.requires ?
