name: CI

on: [pull_request, workflow_dispatch]

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint code
        run: |
          pipx run nox -s check_code

      - name: Check format
        run: |
          pipx run nox -s check_format

      - name: Type check
        run: |
          pipx run nox -s check_types

      - name: Build docs
        run: |
          pipx run nox -s docs

      - name: Build wheel
        run: |
          pipx run nox -s build

  tests:
    name: Test Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Test
        run: |
          pipx run nox -s coverage --python ${{ matrix.python_version }}
