name: CI

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Poetry setup
      run: |
        python -m pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    #- name: Build packages
    #  run: |
    #    poetry build
  
    - name: Lint with mypy
      run: |
        poetry run mypy mousebender

    - name: Check format with Black
      run: |
        poetry run black --check .

    - name: Test with pytest
      run: |
        poetry run pytest --cov

    #- name: Capture artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: packages
    #    path: dist/

    env:
      PYTHONDEVMODE: 1
