name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  tests:
    if: github.event.action != 'closed' || github.event.pull_request.merged

    name: Test Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python_version: ['3.5', '3.6', '3.7', '3.8']
    env:
      PYTHONDEVMODE: 1

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Poetry setup
      run: |
        python -m pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint with mypy
      run: |
        poetry run mypy mousebender
  
    - name: Check format with Black
      if: matrix.python_version!='3.5'
      run: |
        poetry run black --check .

    - name: Test with pytest
      run: |
        poetry run pytest --cov



  release:
    needs: [tests]
    if: github.event_name == 'pull_request' && github.ref == 'master' && github.event.action == 'closed' && github.event.pull_request.merged

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: brettcannon/release-often@master
      with:
        changelog-path: CHANGELOG.rst
        pypi-token: ${{ secrets.PYPI_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
