name: Release

on:
  push:
    branches:
      - master

jobs:
    tests:
    name: Test Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
        # CI for PRs handle other versions;
        # this is just a safeguard.
        python_version: ['3.8']
    env:
        PYTHONDEVMODE: 1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
        uses: actions/setup-python@v1
        with:
        python-version: ${{ matrix.python_version }}

    - name: Poetry setup
      run: |
        python -m pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint with flake8
      run: |
        poetry run flake8

    - name: Lint with mypy
      run: |
        poetry run mypy mousebender

    - name: Check format with Black
      run: |
        poetry run black --check .

    - name: Test with pytest
      run: |
        poetry run pytest --cov

  release:
    needs: [test]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: brettcannon/release-often@master
      with:
        changelog-path: CHANGELOG.rst
        pypi-token: ${{ secrets.PYPI_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
